title: A blog about Life
author: Benjamin .M. Kyamanywa
email: benjaminkyam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my blog. This is a walkthrough journey on the beauty of life and growth.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minimaYou can check out the _config.yml file on the Code tab of your repository.

￼ Activity: Modify the config file
Let's change the _config.yml so it's a perfect fit for your new blog. First, we need to use a blog-ready theme. For this activity, we will use a theme named minima.

Navigate to the Code tab of this repository, and browse to the _config.yml file.
