title: A blog about Life
author: Benjamin Kyamanywa
email: benjaminkyam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  There are many things that we love about life and these things help us 
  grow with every challenge they present us with on our through life.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
